#!/bin/sh
### BEGIN INIT INFO
# Provides:          payment_daemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start an odoo instance at boot time
# Description:       Enable service provided by odoo.
### END INIT INFO

cmd="./merchant.py"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/odoo/$name.log"
stderr_log="/var/log/odoo/$name.log"
user=odoo
dir="/home/odoo/odoo-dev/deploy/daemon"
password="a"
get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name"
        cd "$dir"
        sudo $cmd stop $password
        #Wait to database close
        sleep 1
        for i in {1..10}
        do
            if is_running; then
                echo -n "."
                sleep 1
            fi
        done
        echo

        #kill `get_pid`
        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            $0 stop
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
